# Change these first
owner: cheprasov-dev
repo: upptime-board

sites:
  - name: Google
    url: https://www.google.com
    group: CRM
  - name: Wikipedia
    url: https://en.wikipedia.org
    group: CRM
  - name: Hacker News
    url: https://news.ycombinator.com
    group: HRD
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
    group: HRD
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true
  - name: Broken Test
    url: https://chatgpt.com/
  - name: Broken Test 2
    url: https://doesnotexist.cheprasov.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-board
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
